import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/navbar";
import PageFooter from "@/components/layout/footer";

const lato = Lato({ subsets: ['latin-ext'],weight:['400'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={lato.className}>
        <header>
          <NavBar />

        </header>
        {children}
        <footer>
          <PageFooter/>
        </footer>
        </body>
      
    </html>
  );
}
